# Generated by Django 5.0.2 on 2025-10-17 01:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0002_administradores_delete_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='edad',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{10}$', 'El telefono debe de tener 10 digitos')]),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='update',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
