# Generated by Django 5.0.2 on 2025-10-17 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0003_alter_administradores_edad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administradores',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='rfc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='telefono',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='administradores',
            name='update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
