# Generated by Django 5.0.2 on 2025-12-01 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dev_sistema_escolar_api', '0009_eventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventos',
            name='programa_educativo',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventos',
            name='publico_objetivo',
            field=models.TextField(max_length=255),
        ),
    ]
